DOMAIN-SUFFIX,webofknowledge.com
DOMAIN-SUFFIX,webofscience.com
DOMAIN-SUFFIX,clarivate.com
DOMAIN-SUFFIX,clarivate.cn
DOMAIN-SUFFIX,clarivate.net
DOMAIN-SUFFIX,acm.org
DOMAIN-SUFFIX,dl.acm.org
DOMAIN-SUFFIX,acs.org
DOMAIN-SUFFIX,aip.org
DOMAIN-SUFFIX,aip.scitation.org
DOMAIN-SUFFIX,aom.org
DOMAIN-SUFFIX,aps.org
DOMAIN-SUFFIX,arxiv.org
DOMAIN-SUFFIX,blackwell-synergy.com
DOMAIN-SUFFIX,cabdirect.org
DOMAIN-SUFFIX,cambridge.org
DOMAIN-SUFFIX,cnki.com.cn
DOMAIN-SUFFIX,cnki.net
DOMAIN-SUFFIX,cqvip.com
DOMAIN-SUFFIX,deepdyve
DOMAIN-SUFFIX,doi.org
DOMAIN-SUFFIX,els-cdn
DOMAIN-SUFFIX,elsevier
DOMAIN-SUFFIX,elsevier.cn
DOMAIN-SUFFIX,elsevier.com
DOMAIN-SUFFIX,elsevierhealth.com
DOMAIN-SUFFIX,ieee.org
DOMAIN-SUFFIX,ieeexplore.ieee.org
DOMAIN-SUFFIX,iop.org
DOMAIN-SUFFIX,jstor.org
DOMAIN-SUFFIX,nature.com
DOMAIN-SUFFIX,ncbi.nlm.nih.gov
DOMAIN-SUFFIX,nih.gov
DOMAIN-SUFFIX,onlinelibrary.wiley.com
DOMAIN-SUFFIX,osapublishing.org
DOMAIN-SUFFIX,oup.com
DOMAIN-SUFFIX,oxfordjournals.org
DOMAIN-SUFFIX,pkulaw
DOMAIN-SUFFIX,proquest.com
DOMAIN-SUFFIX,readcube
DOMAIN-SUFFIX,relx.com
DOMAIN-SUFFIX,researchgate.net
DOMAIN-SUFFIX,rsc.org
DOMAIN-SUFFIX,sagepub.com
DOMAIN-SUFFIX,sciencedirect
DOMAIN-SUFFIX,sciencedirect.com
DOMAIN-SUFFIX,sciencemag.org
DOMAIN-SUFFIX,scite.ai
DOMAIN-SUFFIX,scopus.com
DOMAIN-SUFFIX,springer.com
DOMAIN-SUFFIX,springerlink.com
DOMAIN-SUFFIX,springernature.com
DOMAIN-SUFFIX,tandfonline.com
DOMAIN-SUFFIX,wanfangdata
DOMAIN-SUFFIX,wanfangdata.com.cn
DOMAIN-SUFFIX,wiley.com
DOMAIN-SUFFIX,cabdirect.org
DOMAIN-SUFFIX,westlawchina
DOMAIN-SUFFIX,lex-localis.org
